function check_login(){if(typeof arguments[0]=='string'){var provider=arguments[0];var onSuccess=arguments[1];}else{var provider='';var onSuccess=arguments[0]}
$j.post('/phpscripts/checkLogin.php/',{provider:provider,onSuccess:onSuccess},check_login_return,"json");}
function check_login_return(){var return_data=arguments[0];var onSuccess=return_data.onSuccess;var provider=return_data.provider||'';if(return_data.return_code==0){if(onSuccess){window[onSuccess[0]].apply(this,onSuccess.slice(1));}}else{var dialogObject={language:'cn',dialog:'#login',postLoad:['f022_init',provider]}
dialogObject['provider']=provider;if(onSuccess){dialogObject['onSuccess']=onSuccess;}
setup_dialog(dialogObject);}}
function process_logged_in(){var return_data=arguments[0];if(return_data.return_code=='failed'){alert('你选择的社交网站暂时不能登陆，请稍后再试。');$j('#login_loading').remove();$j('#login').show();}else if(return_data.return_code=='new'){setup_dialog({language:'cn',dialog:'#acceptTerms',onSuccess:return_data.onSuccess});}else if(return_data.onSuccess){var onSuccess=return_data.onSuccess
window[onSuccess[0]].apply(this,onSuccess.slice(1));$j('#login').dialog('close');$j('#header_area').html(return_data.header_html);if(post_login_action){post_login_action();}}else{window.location.reload();}}
function logout(){$j.post('/phpscripts/submitLogout.php',{},function(){var return_code=arguments[0];$j('#header_area').html('<img src="/images/blue_circles.gif" style="margin:4px;height:32px;" />');window.location.reload();},'json');}
String.prototype.trim=function(){return this.replace(/^\s+|\s+$/,'');};String.prototype.repeat=function(rTimes){var new_string='';for(i=0;i<rTimes;i++){new_string+=this;}return new_string;};String.prototype.lpad=function(pad,pLength){if(this.length>pLength){return this;}else{return pad.repeat(pLength-this.length)+this;}};function stopEventPropagation(evt){if(!evt){evt=window.event;}
evt.cancelBubble=true;if(evt.stopPropagation)evt.stopPropagation();}
function get_target(evt){return(!evt?window.event.srcElement:(evt.srcElement?$j(evt.srcElement):$j(evt.target)));}
function is_email_valid(email){var email_valid=0;var rx=/^[\w\.-]+@[\w\.-]+\.\w+$/i;if(email.length>80){email_valid=1;}else if(email.length==0){email_valid=3;}else if(!rx.test(email)){email_valid=2;}else{email_valid=0;}
return email_valid;}
function show_error_message(error_div,error_title,error_message){var button_object=new Object;$j('#'+error_div).dialog('option','title',error_title);button_object[$defaultText['cancel']]=function(){$j(this).dialog('close');};$j('#'+error_div).dialog('option','buttons',button_object);$j('#'+error_div).html('<div class="topMargin16 FormDetailHeading">'+error_message+'</div>');$j('#'+error_div).dialog('open');}
function show_info_message(info_div,info_title,info_message){var button_object=new Object;$j('#'+info_div).dialog('option','title',info_title);button_object[$defaultText['okay']]=function(){$j(this).dialog('close');};$j('#'+info_div).dialog('option','buttons',button_object);$j('#'+info_div).html('<div class="topMargin16 FormDetailHeading">'+info_message+'</div>');$j('#'+info_div).dialog('open');}
function validate_postcode_1(input_object,mandatory){$j(input_object).val($j(input_object).val().toUpperCase());if(mandatory&&$j(input_object).length==0){$j(input_object).addClass('invalidInput');}else if(!mandatory&&$j(input_object).length==0){$j(input_object).removeClass('invalidInput');}else if(/^[A-Z]\d[A-Z]/.test($j(input_object).val())){$j(input_object).removeClass('invalidInput');}else{$j(input_object).addClass('invalidInput');};}
function validate_postcode_2(input_object,mandatory){$j(input_object).val($j(input_object).val().toUpperCase());if(mandatory&&$j(input_object).val().length==0){$j(input_object).addClass('invalidInput');}else if(!mandatory&&$j(input_object).val().length==0){$j(input_object).removeClass('invalidInput');}else if(/^\d[A-Z]\d/.test($j(input_object).val())){$j(input_object).removeClass('invalidInput');}else{$j(input_object).addClass('invalidInput');};}
function validate_area_code(input_object,mandatory){if(mandatory&&$j(input_object).val().length==0){$j(input_object).addClass('invalidInput');}else if(!mandatory&&$j(input_object).val().length==0){$j(input_object).removeClass('invalidInput');}else if(/^\d{3}/.test($j(input_object).val())){$j(input_object).removeClass('invalidInput');}else{$j(input_object).addClass('invalidInput');};}
function is_mandatory(input_object){$j(input_object).val($j(input_object).val().trim());if($j(input_object).val().length==0){$j(input_object).addClass('invalidInput');}else{$j(input_object).removeClass('invalidInput');}}
function htmlEncode(value){if(value){return $j('<div />').text(value).html();}else{return'';}}
function htmlDecode(value){if(value){return $j('<div />').html(value).text();}else{return'';}}
function loadGoogleMap(){apikey=arguments[0];callback=arguments[1];if(typeof google!='object'||typeof google.maps!='object'){var script=document.createElement("script");script.type="text/javascript";var apikey=(apikey?'&key='+apikey:'');var callback=(callback?'&callback='+callback:'');script.src="http://maps.googleapis.com/maps/api/js?sensor=false"+apikey+callback;document.body.appendChild(script);}else{window[callback].apply()}}
function place_products(divName,prodArray,append,option){if(typeof option!='undefined'){if(typeof option.padding!='undefined'){var padding=option.padding;}else{var padding=5;}
if(typeof option.image_width!='undefined'){var image_width=option.image_width;}else{var image_width=180;}
if(typeof option.v_padding!='undefined'){var v_padding=option.v_padding;}else{var v_padding=padding;}}else{var padding=5;var image_width=180;var v_padding=padding;}
var frame_width=(image_width+2*padding);var wrapper=$j(divName);var totalWidth=wrapper.innerWidth();var totalCols=Math.floor((totalWidth-(2*padding))/frame_width);var total=prodArray['products'].length;var start=wrapper.children().length;if(append&&start>0){total+=wrapper.children().length;var divHeight=wrapper.height();}else{window['$prodPosArray']=new Array();var divHeight=0;}
var totalRows=Math.ceil(total/totalCols);var row_start=window['$prodPosArray'].length;for(i=row_start;i<totalRows;i++){$prodPosArray[i]=new Array();}
wrapper.data('cols',totalCols);var left=0;var top=0;var height=0;for(var i=0;i<prodArray['products'].length;i++){var col=(i+start)%totalCols;var row=Math.floor((i+start)/totalCols);var product_html=prodArray['products'][i];left=col*frame_width+padding;if(row==0){top=0;}else{top=$prodPosArray[row-1][col]['top']+$prodPosArray[row-1][col]['height']+v_padding*2;}
product_html=product_html.replace(/left:\s*[0-9]+px/,'left:'+left+'px');product_html=product_html.replace(/top:\s*[0-9]+px/,'top:'+top+'px');wrapper.append(product_html);height=wrapper.children().eq(i+start).outerHeight();$prodPosArray[row][col]={top:top,height:height};divHeight=Math.max(divHeight,top+height+v_padding*4);}
wrapper.css({height:divHeight});if(append){wrapper.data('from',wrapper.children().length);}
if(prodArray['more']=='Y'){$j('#moreProductBtn').show();}else{$j('#moreProductBtn').hide();}}
function place_products_mobile(divName,prodArray,append){var wrapper=$j(divName);var totalWidth=wrapper.innerWidth();var totalCols=Math.floor((totalWidth-10)/190);var total=prodArray['products'].length;var start=wrapper.children().length;if(append&&start>0){total+=wrapper.children().length;var divHeight=wrapper.height();}else{window['$prodPosArray']=new Array();var divHeight=0;}
var totalRows=Math.ceil(total/totalCols);var row_start=window['$prodPosArray'].length;for(i=row_start;i<totalRows;i++){$prodPosArray[i]=new Array();}
wrapper.data('cols',totalCols);var left=0;var top=0;var height=0;for(i=0;i<prodArray['products'].length;i++){var col=(i+start)%totalCols;var row=Math.floor((i+start)/totalCols);var product_html=prodArray['products'][i];left=col*190+5;if(row==0){top=0;}else{top=$prodPosArray[row-1][col]['top']+$prodPosArray[row-1][col]['height']+10;}
product_html=product_html.replace(/left:\s*[0-9]+px/,'left:'+left+'px');product_html=product_html.replace(/top:\s*[0-9]+px/,'top:'+top+'px');wrapper.append(product_html);height=wrapper.children().eq(i+start).outerHeight();$prodPosArray[row][col]={top:top,height:height};divHeight=Math.max(divHeight,top+height+20);}
wrapper.css({height:divHeight});if(append){wrapper.data('from',wrapper.children().length);}
if(prodArray['more']=='Y'){$j('#moreProductBtn').show();}else{$j('#moreProductBtn').hide();}}
function scroll_photo(){var next_index=parseInt($j('#photo_scroll').data('scroll_index'))+1;var thumbnail_index=(next_index==$j('#photo_scroll').data('count')?0:next_index);$j('#photo_thumbnails>img:eq('+thumbnail_index+')').addClass('selected').siblings().removeClass('selected');$j('#photo_scroll').animate({left:-(next_index*308)},800,function(){if(thumbnail_index==0){$j('#photo_scroll').css({left:0})};$j('#photo_scroll').data('scroll_index',thumbnail_index);window['$scrollTimer']=setTimeout(scroll_photo,5000);});}
function update_comment_count(text_object,count_object,max_length,text_options){if(typeof(text_object)!='object'){return}
var text_string=text_object.val().trim();var errorClass=(text_options?(text_options.errorClass?text_options.errorClass:'alertWords'):'alertWords');if(text_options){text_string=(text_options.prefix||'')+text_string;}
if(link_match=text_string.match(/\bhttp[s]?:\/\/[^\x20]+\b/g)){var num_links=link_match.length;text_string=text_string.replace(/\bhttp[s]?:\/\/[^\x20]+\b/g,'');}else{var num_links=0;}
if(latin_match=text_string.match(/[\u0000-\u00ff]/g)){var num_latin=latin_match.length;}else{var num_latin=0;}
var chars_left=max_length-(10*num_links+text_string.length-Math.floor(num_latin/2));if(chars_left<0){count_object.text('('+chars_left+')');count_object.addClass(errorClass);}else{count_object.text(chars_left);count_object.removeClass(errorClass);}
return chars_left;}
function update_text_count(text_object,count_object,max_length,text_options){var text_string;if(typeof(text_object)=='object'){text_string=text_object.val();if(text_options&&text_options.excludeURL){text_string=text_string.replace(/\bhttp[s]?:\/\/[^\x20]+\b/g,'');}}else{return}
var chars_left=max_length-count_unicode_length(text_string);var errorClass=(text_options?(text_options['errorClass']?text_options['errorClass']:'alertWords'):'alertWords');var num_bytes=(text_options?(text_options['bytes']?text_options['bytes']:3):3);if(chars_left<0){count_object.text('('+Math.floor(chars_left/num_bytes)+')');count_object.addClass(errorClass);}else{count_object.text(Math.floor(chars_left/num_bytes));count_object.removeClass(errorClass);}
return chars_left;}
function count_unicode_length(raw_string,text_options){if(text_options&&text_options.excludeURL){raw_string=raw_string.replace(/\bhttp[s]?:\/\/[^\x20]+\b/g,'');}
var escapedStr=encodeURI(raw_string);if(escapedStr.indexOf("%")!=-1){var count=escapedStr.split("%").length-1;if(count==0)count++;var tmp=escapedStr.length-(count*3);count+=tmp;}else{count=escapedStr.length;}
return count;}
function show_wb_comments(status_id){$j('#wb_tabs_'+status_id+',#wb_status_'+status_id+'_cmts').show();update_comment_count($j('#wb_status_'+status_id+'_cmt'),$j('#wb_count_'+status_id+'_cmt'),$weiboCount-15);if($j('#wb_status_'+status_id+'_cmts').is(':empty')){$j('#wb_status_'+status_id+'_cmts').html('<div class="fltlft"></div><div class="fltrt wb_cmt_navi"></div><div style="clear:both"></div>');get_wb_comments(1,20,status_id);}}
function get_wb_comments(page_num,page_size,status_id){var $weiboCommentData={page_num:page_num,page_func:'get_wb_comments('+status_id+')',size:10,status_id:status_id};$weiboCommentData['from']=(page_num-1)*$weiboCommentData.size;var comment_div=$j('#wb_status_'+status_id+'_cmts');comment_div.show().find('.wb_cmt_navi').html('<img src="/images/blue_circles.gif" class="loading" />');$j.post('/server/getWeiboComments.php',$weiboCommentData,function(return_data){$j('#comments_'+status_id+',#comments_'+status_id+'_tab').text(return_data.total);var html=return_data.html;html+='<div class="fltlft">'+return_data.page_info+'</div>';html+='<div class="fltrt wb_cmt_navi">'+return_data.page_navi+'</div>';html+='<div style="clear:both"></div>';comment_div.html(html);},'json');}
function show_wb_reposts(status_id){$j('#wb_tabs_'+status_id+',#wb_status_'+status_id+'_reposts').show();update_comment_count($j('#wb_status_'+status_id+'_repost'),$j('#wb_count_'+status_id+'_repost'),$weiboCount-15);if($j('#wb_status_'+status_id+'_reposts').is(':empty')){$j('#wb_status_'+status_id+'_reposts').html('<div class="fltlft"></div><div class="fltrt wb_repost_navi"></div><div style="clear:both"></div>');get_wb_reposts(1,20,status_id);}}
function get_wb_reposts(page_num,page_size,status_id){var $weiboCommentData={page_num:page_num,page_func:'get_wb_reposts('+status_id+')',size:10,status_id:status_id};$weiboCommentData['from']=(page_num-1)*$weiboCommentData.size;var comment_div=$j('#wb_status_'+status_id+'_reposts');comment_div.show().find('.wb_repost_navi').html('<img src="/images/blue_circles.gif" class="loading" />');$j.post('/server/getWeiboReposts.php',$weiboCommentData,function(return_data){$j('#reposts_'+status_id+',#reposts_'+status_id+'_tab').text(return_data.total);var html=return_data.html;html+='<div class="fltlft">'+return_data.page_info+'</div>';html+='<div class="fltrt wb_repost_navi">'+return_data.page_navi+'</div>';html+='<div style="clear:both"></div>';comment_div.html(html);},'json');}
function get_map_accuracy(){var location_types=arguments[0];var index=0;var num_types=location_types.length;var accuracy=0,found=false;while(index<num_types&&!found){switch(location_types[index]){case'establishment':case'premise':case'subpremise':case'transit_station':found=true;accuracy=9;break;case'street_address':found=true;accuracy=8;break;case'intersection':found=true;accuracy=7;break;case'route':found=true;accuracy=6;break;case'postal_code':found=true;accuracy=5;break;case'sublocality':found=true;accuracy=4;break;case'locality':found=true;accuracy=3;break;case'administrative_area_level_1':case'administrative_area_level_2':case'administrative_area_level_3':found=true;accuracy=2;break;case'country':found=true;accuracy=1;break;}
index+=1;}
return accuracy;}
function get_accuracy_label(){var language=arguments[0];var geocode_accuracy=arguments[1];var accuracy_label;switch(language){case'tw':switch(geocode_accuracy){case 0:accuracy_label='地址不詳';break;case 1:accuracy_label='國家';break;case 2:accuracy_label='州、省';break;case 3:accuracy_label='市、鎮、村';break;case 4:accuracy_label='市區、地區';break;case 5:accuracy_label='郵政編號';break;case 6:accuracy_label='街道名稱';break;case 7:accuracy_label='最近街道交界';break;case 8:accuracy_label='街道門牌';break;case 9:accuracy_label='大廈、商場';break;case 10:accuracy_label='手動設定';break;};break;case'cn':switch(geocode_accuracy){case 0:accuracy_label='地址不详';break;case 1:accuracy_label='国家';break;case 2:accuracy_label='州、省';break;case 3:accuracy_label='市、镇、村';break;case 4:accuracy_label='市区、地区';break;case 5:accuracy_label='邮政编码';break;case 6:accuracy_label='街道名称';break;case 7:accuracy_label='最近街道交界';break;case 8:accuracy_label='街道门牌';break;case 9:accuracy_label='大厦、商场';break;case 10:accuracy_label='手动设定';break;};break;case'en':default:switch(geocode_accuracy){case 0:accuracy_label='address unknown';break;case 1:accuracy_label='country';break;case 2:accuracy_label='state/province';break;case 3:accuracy_label='county/municipality';break;case 4:accuracy_label='city/town/village';break;case 5:accuracy_label='postcode/zip code';break;case 6:accuracy_label='street name';break;case 7:accuracy_label='nearest intersection';break;case 8:accuracy_label='street number';break;case 9:accuracy_label='building';break;case 10:accuracy_label='manual';break;};break;}
return accuracy_label;}
function findGoogleGeopoint(geocodeOptions,geocodeObject,mapObject){if(!window['$GoogleGeocoder']){window['$GoogleGeocoder']=new google.maps.Geocoder();}
$GoogleGeocoder.geocode(geocodeOptions,function(results,status){findGoogleGeopointReturn(results,status,geocodeObject,mapObject);});}
function findGoogleGeopointReturn(results,status,geocodeObject,mapObject){var geocoder_results=arguments[0][0];window['$GoogleGeocoderStatus']=arguments[1];if(window['$GoogleGeocoderStatus']==google.maps.GeocoderStatus.OK){if(geocodeObject['geoaddress_id']){geocodeObject['geo_address']=$j(geocodeObject['geoaddress_id']).val();}
geocodeObject['lat_point']=geocoder_results.geometry.location.lat();geocodeObject['long_point']=geocoder_results.geometry.location.lng();geocodeObject['address_type']=geocoder_results.types;geocodeObject['formatted_address']=geocoder_results.formatted_address;geocodeObject['address_components']=geocoder_results.address_components;var accuracy=get_map_accuracy(geocoder_results.types);if(geocodeObject['accuracy_id']){$j(geocodeObject['accuracy_id']).text(get_accuracy_label(geocodeObject['accuracy_lang'],accuracy));}
switch(geocoder_results.geometry.location_type){case google.maps.GeocoderLocationType.ROOFTOP:BM_precision='P';break;case google.maps.GeocoderLocationType.RANGE_INTERPOLATED:BM_precision='I';break;case google.maps.GeocoderLocationType.GEOMETRIC_CENTER:BM_precision='C';break;case google.maps.GeocoderLocationType.APPROXIMATE:BM_precision='A';break;}
var zoom;if(accuracy<=1){zoom=11;}
else if(accuracy>=7){zoom=17;}
else{zoom=10+parseInt(accuracy);}
geocodeObject['zoom']=zoom;mapObject.lat=geocodeObject.lat_point;mapObject.long=geocodeObject.long_point;mapObject.zoom=zoom;setGoogleMap(mapObject);}else{var status_label;switch(window['$GoogleGeocoderStatus']){case google.maps.GeocoderStatus.ERROR:status_label='無法連線到地圖服務';break;case google.maps.GeocoderStatus.INVALID_REQUEST:status_label='查詢格式不正確';break;case google.maps.GeocoderStatus.OVER_QUERY_LIMIT:status_label='超額查詢';break;case google.maps.GeocoderStatus.REQUEST_DENIED:status_label='拒絕查詢';break;case google.maps.GeocoderStatus.UNKNOWN_ERROR:status_label='不明錯誤';break;case google.maps.GeocoderStatus.ZERO_RESULTS:status_label='找不到合適的結果';break;}
if(geocodeObject['accuracy_id']){$j(geocodeObject['accuracy_id']).text('搜索錯誤：'+status_label);}}}
function setGoogleMap(mapObject){var point=new google.maps.LatLng(mapObject.lat,mapObject.long);var myOptions={scrollwheel:false,zoom:mapObject.zoom,center:point,mapTypeId:google.maps.MapTypeId.ROADMAP};mapObject.map=new google.maps.Map(document.getElementById(mapObject.map_id.replace(/^\#/,'')),myOptions);var bizMarkerImage=new google.maps.MarkerImage('/artwork/mm_green_home.png',new google.maps.Size(20,40),new google.maps.Point(0,0),new google.maps.Point(10,38));var bizMarkerShadow=new google.maps.MarkerImage('/artwork/mm_shadow.png',new google.maps.Size(44,40),new google.maps.Point(0,0),new google.maps.Point(10,40));mapObject.marker=new google.maps.Marker({position:point,map:mapObject.map,icon:bizMarkerImage,shadow:bizMarkerShadow,draggable:true,animation:google.maps.Animation.DROP});}
function linkifyYouTubeURLs(text){var re=/https?:\/\/(?:[0-9A-Z-]+\.)?(?:youtu\.be\/|youtube\.com\S*[^\w\-\s])([\w\-]{11})(?=[^\w\-]|$)(?![?=&+%\w]*(?:['"][^<>]*>|<\/a>))[?=&+%\w-]*/ig;return text.replace(re,'<iframe width="540" height="304" src="http://www.youtube.com/embed/$1?wmode=opague&rel=0&controls=0&showinfo=0" frameborder="0" allowfullscreen></iframe>');}
function weibofy(wb_text,wbObject){var status_id;for(i=0;i<window[wbObject]['ids'].length;i++){status_id=String(window[wbObject]['ids'][i]);if(window[wbObject][status_id]){wb_text=wb_text.replace('[weibo:'+status_id+']',window[wbObject][status_id]['html']);}}
return wb_text;}
function $stripTextHTML(text){return text.replace(/(<([^>]+)>)/ig,'')}
function $stripBlogHTML(text){var re=/(<(?!\/?(h[1-9]|img|span|b|strong|i|font))([^>]+)>)/ig;return text.replace(re,'');}
function $replaceBlogLF(text){var re=/\<br\040*\/?\>/ig;return text.replace(re,String.fromCharCode(10));}
(function($j,undefined){$j.fn.getCursorPosition=function(){var el=$j(this).get(0);var pos=0;if('selectionStart'in el){pos=el.selectionStart;}else if('selection'in document){el.focus();var Sel=document.selection.createRange();var SelLength=document.selection.createRange().text.length;Sel.moveStart('character',-el.value.length);pos=Sel.text.length-SelLength;}
return pos;}
$j.fn.htmledit=function(type){var start_pos=$j(this)[0].selectionStart;var end_pos=$j(this)[0].selectionEnd;var text=$j(this).val();var new_text;switch(type){case'bold':new_text=text.substr(0,start_pos)+'<b>'+text.substring(start_pos,end_pos)+'</b>'+text.substring(end_pos);break;case'italics':new_text=text.substr(0,start_pos)+'<i>'+text.substring(start_pos,end_pos)+'</i>'+text.substring(end_pos);break;case'add indent':new_text=text.substr(0,start_pos)+'<div style="padding-left:40px;">'+text.substring(start_pos,end_pos)+'</div>'+text.substring(end_pos);break;case'image description':new_text=text.substr(0,start_pos)+'<span style="font-size:12px; color:#666666">'+text.substring(start_pos,end_pos)+'</span>'+text.substring(end_pos);break;}
$j(this).val(new_text);}
$j.fn.setCursorPosition=function(pos){if($j(this).get(0).setSelectionRange){$j(this).get(0).setSelectionRange(pos,pos);}else if($j(this).get(0).createTextRange){var range=$j(this).get(0).createTextRange();range.collapse(true);range.moveEnd('character',pos);range.moveStart('character',pos);range.select();}}})(jQuery);(function($j){var re=/([^&=]+)=?([^&]*)/g;var decodeRE=/\+/g;var decode=function(str){return decodeURIComponent(str.replace(decodeRE," "));};$j.parseParams=function(query){var params={},e;while(e=re.exec(query)){var k=decode(e[1]),v=decode(e[2]);if(k.substring(k.length-2)==='[]'){k=k.substring(0,k.length-2);(params[k]||(params[k]=[])).push(v);}
else params[k]=v;}
return params;};})(jQuery);(function($j){var proto=$j.ui.autocomplete.prototype,initSource=proto._initSource;function filter(array,term){var matcher=new RegExp($j.ui.autocomplete.escapeRegex(term),"i");return $j.grep(array,function(value){return matcher.test($j("<div>").html(value.label||value.value||value).text());});}
$j.extend(proto,{_initSource:function(){if(this.options.html&&$j.isArray(this.options.source)){this.source=function(request,response){response(filter(this.options.source,request.term));};}else{initSource.call(this);}},_renderItem:function(ul,item){return $j("<li></li>").data("item.autocomplete",item).append($j("<a></a>")[this.options.html?"html":"text"](item.label)).appendTo(ul);}});})(jQuery);