<?php 
$disclaimer='<p>Disclaimer: This representation is based in whole or in part on data generated by the Chilliwack & District Real Estate Board, Fraser Valley Real Estate Board or Real Estate Board of Greater Vancouver which assumes no responsibility for its accuracy. </p>';
?>
  <div class="footer-container">
    <div class="container">
      <!-- Footer box -->
      <div class="footer-top">
        <div class="row">
          <div class="span4">
            <h3>contact us 联系我们</h3>
            <p>Should you have any questions, feel free to contact us.</p>
            <p>如果您有任何问题，欢迎随时与我联系！我和我的团队一定会竭诚为您服务！</p>
            <span>Royal Pacific Realty Corp. </span><br/>
            <span>Oakridge Office</span><br/>
            <span>Address 地址. North Tower 550 - 650 West 41st Avenue, Vancouver, BC V5Z 2M9</span><br/>
            <span>Phone 电话. 604.356.0707 </span><br/>
            <span>Fax 传真. 604.266.8829 </span><br/>
            <span>Mail 邮箱. <a href="mailto:allison.jiang@yahoo.com?Subject=Hello%20again">allison.jiang@yahoo.com</a>  </span><br/>
          </div>
          <div class="span4">
          
          </div>
          <div class="span4">
            <h3>don’t miss out 订阅邮件</h3>
            <p>Stay up to date with lasted housing market information.</p>
            <p>欢迎订阅我们的邮件，这样您就能获得我们为您提供的最新资讯了！<p>
            <div class="newletter">
              <form>
                <input type="text" class="textnewletter" placeholder="Enter your email here…">
                <button type="submit" class="buttonnewletter">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- End Footer box -->
      <div class="footer-bottom">
        <div class="row">
          <div class="span6">
          <p>Disclaimer: This representation is based in whole or in part on data generated by the Chilliwack & District Real Estate Board, Fraser Valley Real Estate Board or Real Estate Board of Greater Vancouver which assumes no responsibility for its accuracy. </p>
            <p>This site's content is the responsibility of Allison Jiang, licensed REALTOR®(s) in the Province of British Columbia. The trademarks REALTOR®, REALTORS®, MLS®, Multiple Listing Service®, and the associated logos are controlled by The Canadian Real Estate Association (CREA) and identify real estate professionals who are members of CREA.</p>
            <p>© 2014, All Rights Reserved</p>
          </div>
          <div class="span6">
            <div class="social pull-right">
              <ul>
                <li><a class="email" title="" href="mailto:allison.jiang@yahoo.com?Subject=Hello%20again"> Email </a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
